on:
  push:
    branches:
      - main
name: Build and Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          target: wasm32-unknown-unknown
      - uses: taiki-e/install-action@wasm-pack
      - name: Annotate commit with clippy warnings
        uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.15.0'
      - run: npm install
      - run: npm test
      - run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
      - run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"

      # - uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: .

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest 
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   permissions:
  #     pages: write
  #     id-token: write
  #     contents: write
  #   steps:
  #     # - uses: actions/download-artifact@v4
  #     #   with:
  #     #     name: dist
  #     #     path: dist
  #     # - name: Checkout
  #     #   uses: actions/checkout@v4.1.7
  #     # - name: Setup Pages
  #     #   uses: actions/configure-pages@v3
  #     # - uses: actions/upload-pages-artifact@v3
  #     #   with:
  #     #     path: './dist'
  #     # - name: Deploy to GitHub Pages
  #     #   id: deployment
  #     #   uses: actions/deploy-pages@v2
  #     - name: Deploy to GitHub Pages
  #       uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         folder: dist
  #     # GitHub Pagesへのデプロイ
  #     # - name: Deploy to GitHub Pages
  #     #   uses: peaceiris/actions-gh-pages@v3
  #     #   with:
  #     #     github_token: ${{ secrets.GITHUB_TOKEN }}
  #     #     publish_dir: ./dist